name: Build Python Executable

on: workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    container: 
      image: centos
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - working-directory: ./python-scripts
        run: python example.py
