name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env: 
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Check CPU and Memory Info
        run: |
          echo "OS Info:"
          cat /etc/os-release
          echo "System Info:"
          uname -a
          echo "CPU Info:"
          lscpu
          echo "Memory Info:"
          free -h
          echo "Disk Info:"
          df -h
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

  container-test-job:
    needs: Explore-GitHub-Actions
    runs-on: ubuntu-latest
    container:
      image: centos:latest
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Check CPU and Memory Info
        run: |
          echo "OS Info:"
          cat /etc/os-release
          echo "System Info:"
          uname -a
          echo "CPU Info:"
          lscpu
          echo "Memory Info:"
          free -h
          echo "Disk Info:"
          df -h

  my_oracle_arm1:
    needs: container-test-job
    runs-on: self-hosted
    container:
      image: ubuntu-latest
      options: --cpus 1 --memory 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Check CPU and Memory Info
        run: |
          echo "【OS Info】"
          cat /etc/os-release
          echo "【System Info】"
          uname -a
          echo "【CPU Info】"
          lscpu
          echo "【Memory Info】"
          free -h
          echo "【Disk Info】"
          df -h
      - name: File System Check
        run: |
          set -x
          ls -alh .
          ls -alh /

  my_oracle_arm2:
    needs: container-test-job
    runs-on: self-hosted
    container:
      image: centos:latest
      options: --cpus 1 --memory 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Check CPU and Memory Info
        run: |
          echo "【OS Info】"
          cat /etc/os-release
          echo "【System Info】"
          uname -a
          echo "【CPU Info】"
          lscpu
          echo "【Memory Info】"
          free -h
          echo "【Disk Info】"
          df -h
      - name: File System Check
        run: |
          set -x
          ls -alh .
          ls -alh /
