name: Oracle Arm Debug
on: workflow_dispatch

jobs:
  build2:
    # needs: build
    runs-on: ARM64
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "user:"
          id
          echo "pwd:"
          pwd
          echo "ls:"
          ls -alh .
          # echo "check workflows:"
          # ls -alh ./.github/workflows/
          # exit 1
      - run: |
          echo "os-release:"
          cat /etc/os-release
          echo "cpu-info:"
          lscpu
          echo "mem-info:"
          free -h
          echo "disk-info:"
          df -h
      - name: Test Docker
        run: |
          docker ps
      # - if: always()
      #   run: |
      #     ls -la ./
      #     rm -rf ./* || true
      #     rm -rf ./.??* || true
      #     ls -la ./

  build:
    needs: build2
    runs-on: ARM64
    container: 
      image: centos
      options: --privileged -v /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Install Docker CLI
        run: |
          dnf --disablerepo '*' --enablerepo extras swap centos-linux-repos centos-stream-repos
          dnf distro-sync
          dnf -y install dnf-plugins-core
          dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      - run: |
          echo "user:"
          id
          echo "pwd:"
          pwd
          echo "ls:"
          ls -alh .
          # echo "check workflows:"
          # ls -alh ./.github/workflows/
      - run: |
          echo "os-release:"
          cat /etc/os-release
          echo "cpu-info:"
          lscpu
          echo "mem-info:"
          free -h
          echo "disk-info:"
          df -h
          sleep 20
      - name: Test Docker
        run: |
          docker ps

  
